apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: op-num-airports-to-db-py
  namespace: default
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: "iad.ocir.io/ochacafens/ochacafe/spark-py:3.2.1"
  imagePullPolicy: Always
  imagePullSecrets: 
    - docker-registry-secret
  mainApplicationFile: oci://spark@ochacafens/lib/num_airports_to_db.py
  deps:
    jars:
      - https://repo1.maven.org/maven2/com/oracle/database/jdbc/ojdbc8/21.3.0.0/ojdbc8-21.3.0.0.jar
  arguments: 
    - "--input_file"
    - "oci://spark@ochacafens/data/airports.csv"
  sparkVersion: "3.2.1"
  restartPolicy:
    type: OnFailure
    onFailureRetries: 3
    onFailureRetryInterval: 10
    onSubmissionFailureRetries: 5
    onSubmissionFailureRetryInterval: 20
  sparkConf:
    spark.sql.hive.metastore.sharedPrefixes: shaded.oracle,com.oracle.bmc
    spark.hadoop.fs.oci.client.hostname: "https://objectstorage.us-ashburn-1.oraclecloud.com"
    spark.hadoop.fs.oci.client.custom.authenticator: "com.oracle.bmc.hdfs.auth.InstancePrincipalsCustomAuthenticator"
    spark.eventLog.enabled: "true"
    spark.eventLog.dir: "oci://spark@ochacafens/history"
  driver:
    cores: 2
    coreLimit: "3000m"
    memory: "2g"
    labels:
      version: 3.2.1
    serviceAccount: spark
    envSecretKeyRefs:
      DB_USER:
        name: db-config-secret
        key: user
      DB_PASSWORD:
        name: db-config-secret
        key: password
      DB_JDBCURL:
        name: db-config-secret
        key: jdbcUrl
  executor:
    cores: 1
    instances: 3
    memory: "2g"
    labels:
      version: 3.2.1

